// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWsxRr6oWSzaZHwpBSTMVUtpIiuV_AG_g',
    appId: '1:612343026282:web:267e9085acf25317ef7013',
    messagingSenderId: '612343026282',
    projectId: 'quiz-app-6232a',
    authDomain: 'quiz-app-6232a.firebaseapp.com',
    storageBucket: 'quiz-app-6232a.appspot.com',
    measurementId: 'G-MXDC7XGNWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfNfb4akIP1KvY8-iJODcc3VSMalpymco',
    appId: '1:612343026282:android:50bdcd12132e1966ef7013',
    messagingSenderId: '612343026282',
    projectId: 'quiz-app-6232a',
    storageBucket: 'quiz-app-6232a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcXrSyUFwC8iKsdv7c3X0_-5bKTQbryf4',
    appId: '1:612343026282:ios:752d63a06feda092ef7013',
    messagingSenderId: '612343026282',
    projectId: 'quiz-app-6232a',
    storageBucket: 'quiz-app-6232a.appspot.com',
    iosClientId: '612343026282-be74vlqg5c3518dklu1j3cmsgm6f73uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcXrSyUFwC8iKsdv7c3X0_-5bKTQbryf4',
    appId: '1:612343026282:ios:752d63a06feda092ef7013',
    messagingSenderId: '612343026282',
    projectId: 'quiz-app-6232a',
    storageBucket: 'quiz-app-6232a.appspot.com',
    iosClientId: '612343026282-be74vlqg5c3518dklu1j3cmsgm6f73uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
